name: Windows - Build & Unit Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  windows-build-unit-tests:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1

    - name: Compile - windows
      run: MSBuild.exe /p:Configuration=Release /p:Platform="x64" src\visual-studio\chuck.vcxproj
      
    - name: Unit Tests - windows
      working-directory: .\src\test\
      run: python test.py ..\visual-studio\x64\Release\chuck.exe
